### ISSUE TITLE
iOS of Sauron: You do not show that the data is sent to Apple

### ISSUE THREAD

**Issue by rugk** [mac4n6/Presentations#1]
You show that the data is collected, but is it send somewhere? 

Could you confirm or do you have some evidence that the data is send to Apple or third-parties?

I think this is what matters...

**Comment by mac4n6** [comment]
I appreciate the comment however this was not in my scope of research for this presentation. I was focusing on "on-disk" artifacts from more of a forensic perspective. I may research "on-the-wire" aspects further however.

**Comment by rugk** [comment]
Okay, thanks for your reply.
